### ISSUE TITLE
New Feature: Automatic Subscription Renewal

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#181]
> I still need the option to automatically renew my subscription. :)

_Originally posted by @thebadgateway in https://github.com/lhy0403/Qv2ray/issues/162#issuecomment-562419357_

**Comment by lhy0403** [comment]
Will do, but the existing config version will NOT be automatically upgraded since Qv2ray is reaching a fast-rolling stage. This means the new version of Qv2ray will crash due to a mismatch of type `SubscriptionConfig`.

This will be an expected result, the temporary workaround is to remove and re-add the subscriptions in the Subscription Window.

This change will be committed in a few days, just to notify, please don't report issues related to this.

Things mentioned above may change, please alway follow the latest post in this thread.

**Comment by lhy0403** [comment]
Target Qv2ray v2.1.
Will bump a config_version when doing this upgrade.

**Comment by DuckSoft** [comment]
This is pretty good done in current version.
Closing.
